### ISSUE TITLE
oauth or oauth2 ???

### ISSUE THREAD

**Issue by tessus** [php/pecl-web_services-oauth#11]
I really would like to know, whether this is oauth or oauth2. The documentation mentions 1.0, but who is still using oauth 1.0?

The documentation should get a bit of an overhaul, eg when it comes to introduction and examples. If this is 1.0 only, myabe you should retire this extension for security reasons?

**Comment by rlerdorf** [comment]
It is only for OAuth 1.0. You don't really need an extension for OAuth 2.0 because it is so simple. This is for legacy systems that are still stuck with supporting 1.0

**Comment by tessus** [comment]
@rlerdorf thx a lot for the info. The sentence _This is for legacy systems that are still stuck with supporting 1.0_ or something similar would be great for https://www.php.net/manual/en/intro.oauth.php
