### ISSUE TITLE
Segfault in checkOAuthRequest()

### ISSUE THREAD

**Issue by rlerdorf** [php/pecl-web_services-oauth#19]
I am seeing an infrequent segfault in checkOAuthRequest() that I am having a hard time reproducing. It is on the `convert_to_long(retval)` call here:
https://github.com/php/pecl-web_services-oauth/blob/master/provider.c#L773

My theory just from reading the code is that since we are repeatedly calling `oauth_provider_call_cb()` with the `return_value` zval* and returning that same `return_value` ptr we probably shouldn't be calling `zval_ptr_dtor(retval)` on it, like we do at https://github.com/php/pecl-web_services-oauth/blob/master/provider.c#L759

@m6w6 have you seen anything similar?

**Comment by m6w6** [comment]
No reports I know of here. Your observation makes totally sense, though! I suspect this is "PHP5" code, which has pretty different effects since PHP7...

**Comment by rlerdorf** [comment]
Not all that sure about the theory. I can't get it to crash with manual testing of that flow hitting all 3 callbacks. It must be something else.

**Comment by m6w6** [comment]
IIRC `convert_to...` did separate in PHP5, but now `zval_ptr_dtor` is called on a zval received from the engine...

Does the probability of a crash change if you return something refcounted from the callbacks, like a numeric string? 

BTW, what's your actual PHP version?

**Comment by rlerdorf** [comment]
PHP 7.3.25 and I haven't been able to come up with a reproducing script. I tried a few different return types from the callbacks, but you are right, something refcounted is a good idea.

**Comment by rlerdorf** [comment]
No crash and Valgrind is happy with:
```php
<?php
require 'tests/oauth.inc';
$ret = "0";

try {
    $provider = new OAuthProvider(creationParams());
    $provider->consumerHandler(function() use (&$ret) {
        return $ret;
    });
    $provider->timestampNonceHandler(function() {
        $ret = "0";
        return $ret;
    });
    $provider->tokenHandler(function() {
        global $ret;
        return $ret;                                                                                                                                                                                                                                          
    });

    $provider->checkOAuthRequest("http://localhost/request_token.php", OAUTH_HTTP_METHOD_GET);

} catch (OAuthException $E) {
    echo OAuthProvider::reportProblem($E);
}
```

**Comment by m6w6** [comment]
Bump @rlerdorf 

Found the issue by typo, but nevertheless ;)

**Comment by rlerdorf** [comment]
Ah, nice! I'll roll this out and see if that is the one I have been seeing sporadically.

**Comment by rlerdorf** [comment]
I think oauth_provider_call_cb() is missing a few `return NULL;` on errors. It looks like it falls through to `return return_value;` which is going to be non-null

**Comment by rlerdorf** [comment]
Something along the lines of:
```diff
diff --git a/provider.c b/provider.c
index e870bae..13ad9d6 100644
--- a/provider.c
+++ b/provider.c
@@ -329,6 +329,7 @@ static zval *oauth_provider_call_cb(INTERNAL_FUNCTION_PARAMETERS, int type) /* {
        php_oauth_provider_fcall *cb = NULL;
        zval args, *pthis;
        char *errstr = "";
+       int cb_ok = TRUE;
 
        pthis = getThis();
        sop = fetch_sop_object(pthis);
@@ -365,21 +366,24 @@ static zval *oauth_provider_call_cb(INTERNAL_FUNCTION_PARAMETERS, int type) /* {
                if (errstr) {
                        php_error_docref(NULL, E_WARNING, "Invalid callback: %s, %s", Z_STRVAL(cb->fcall_info->function_name), errstr);
                        efree(errstr);
+                       cb_ok = FALSE;
                } else {
                        php_error_docref(NULL, E_WARNING, "Invalid callback: %s.", Z_STRVAL(cb->fcall_info->function_name));
                }
        } else if (errstr) {
                php_error_docref(NULL, E_WARNING, "%s", errstr);
                efree(errstr);
+               cb_ok = FALSE;
        }
 
        if (zend_fcall_info_call(cb->fcall_info, &cb->fcall_info_cache, return_value, &args)!=SUCCESS) {
                php_error_docref(NULL, E_ERROR, "Failed calling callback %s", Z_STRVAL(cb->fcall_info->function_name));
+               cb_ok = FALSE;
        }
 
        zval_ptr_dtor(&args);
 
-       return return_value;
+       return cb_ok ? return_value : NULL;
 }
 /* }}} */
```

**Comment by m6w6** [comment]
Yeah, ACK.

But ... looking closely this whole section looks a bit nuts:
https://github.com/php/pecl-web_services-oauth/blob/ea130674cc51a7ad6887e5238d4171e74366ed36/provider.c#L364-L378

Why even call the callback, if it's not callable?
