### ISSUE TITLE
New tag release for php 8.2

### ISSUE THREAD

**Issue by spk** [php/pecl-web_services-oauth#26]
Hi,

The project missing a new release including this fix https://github.com/php/pecl-web_services-oauth/commit/36a08239bf62c6fbc39ce38cf95ed42e098c022d for php 8.2

Thanks,
Laurent

**Comment by pugelarouge** [comment]
Hello lovely php-oauth people,

Is there any chance that the 2.0.8 release will be pushed to pecl soon ?? PHP8.2 compatibility is starting to become an real issue,

Thanks,
Pugelarouge

**Comment by remicollet** [comment]
2.0.9 is released
