### ISSUE TITLE
A tag for 2.0.8 exists but it is not on pecl

### ISSUE THREAD

**Issue by ryandesign** [php/pecl-web_services-oauth#28]
A tag for version 2.0.8 was created in 2022 but that version was not released to https://pecl.php.net/package/oauth.

**Comment by pugelarouge** [comment]
Although I am comfortable building this from source and (currently) using this with php 8.2... obviously it would be better if this made it to pecl.php.net and in turn out to various distributions (ubuntu speaking personally).

I would like to understand what is stopping 2.0.8 being released, and is this something that I can help with ... is it a case of various QA / style issues ? or just a matter or someone with required permissions pushing it through the chain ?

TIA
Pugelarouge

**Comment by dzuelke** [comment]
Any chance you could trigger a release of [2.0.8](https://github.com/php/pecl-web_services-oauth/releases/tag/2.0.8) to PECL, @rlerdorf / @remicollet / @m6w6 ? 🙏

**Comment by remicollet** [comment]
2.0.9 is available on pecl
