### ISSUE TITLE
Mark github as the official repo on pecl.php.net

### ISSUE THREAD

**Issue by Jan-E** [php/pecl-web_services-oauth#9]
@rlerdorf 
https://pecl.php.net/package/oauth still points to http://git.php.net/?p=pecl/web_services/oauth.git for the source, but apparently the sync is broken.

Please update the link on pecl.php.net. And probably it is best to reflect the change as well on git.php.net

**Comment by m6w6** [comment]
I guess this is not an issue anymore? Everything LGTM now?
